//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Solidity.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SolidityParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ISolidityListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.sourceUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSourceUnit([NotNull] SolidityParser.SourceUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.sourceUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSourceUnit([NotNull] SolidityParser.SourceUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.pragmaDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPragmaDirective([NotNull] SolidityParser.PragmaDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.pragmaDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPragmaDirective([NotNull] SolidityParser.PragmaDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.pragmaName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPragmaName([NotNull] SolidityParser.PragmaNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.pragmaName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPragmaName([NotNull] SolidityParser.PragmaNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.pragmaValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPragmaValue([NotNull] SolidityParser.PragmaValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.pragmaValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPragmaValue([NotNull] SolidityParser.PragmaValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVersion([NotNull] SolidityParser.VersionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.version"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVersion([NotNull] SolidityParser.VersionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.versionOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVersionOperator([NotNull] SolidityParser.VersionOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.versionOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVersionOperator([NotNull] SolidityParser.VersionOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.versionConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVersionConstraint([NotNull] SolidityParser.VersionConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.versionConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVersionConstraint([NotNull] SolidityParser.VersionConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportDeclaration([NotNull] SolidityParser.ImportDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportDeclaration([NotNull] SolidityParser.ImportDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.importDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportDirective([NotNull] SolidityParser.ImportDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.importDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportDirective([NotNull] SolidityParser.ImportDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.natSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNatSpec([NotNull] SolidityParser.NatSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.natSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNatSpec([NotNull] SolidityParser.NatSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.contractDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContractDefinition([NotNull] SolidityParser.ContractDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.contractDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContractDefinition([NotNull] SolidityParser.ContractDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.inheritanceSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInheritanceSpecifier([NotNull] SolidityParser.InheritanceSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.inheritanceSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInheritanceSpecifier([NotNull] SolidityParser.InheritanceSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.contractPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContractPart([NotNull] SolidityParser.ContractPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.contractPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContractPart([NotNull] SolidityParser.ContractPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.stateVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateVariableDeclaration([NotNull] SolidityParser.StateVariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.stateVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateVariableDeclaration([NotNull] SolidityParser.StateVariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.usingForDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingForDeclaration([NotNull] SolidityParser.UsingForDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.usingForDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingForDeclaration([NotNull] SolidityParser.UsingForDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.structDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDefinition([NotNull] SolidityParser.StructDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.structDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDefinition([NotNull] SolidityParser.StructDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.constructorDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorDefinition([NotNull] SolidityParser.ConstructorDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.constructorDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorDefinition([NotNull] SolidityParser.ConstructorDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.modifierDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifierDefinition([NotNull] SolidityParser.ModifierDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.modifierDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifierDefinition([NotNull] SolidityParser.ModifierDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.modifierInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifierInvocation([NotNull] SolidityParser.ModifierInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.modifierInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifierInvocation([NotNull] SolidityParser.ModifierInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] SolidityParser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] SolidityParser.FunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.returnParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnParameters([NotNull] SolidityParser.ReturnParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.returnParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnParameters([NotNull] SolidityParser.ReturnParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.modifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifierList([NotNull] SolidityParser.ModifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.modifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifierList([NotNull] SolidityParser.ModifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.eventDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventDefinition([NotNull] SolidityParser.EventDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.eventDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventDefinition([NotNull] SolidityParser.EventDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumValue([NotNull] SolidityParser.EnumValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumValue([NotNull] SolidityParser.EnumValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDefinition([NotNull] SolidityParser.EnumDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDefinition([NotNull] SolidityParser.EnumDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] SolidityParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] SolidityParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] SolidityParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] SolidityParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.eventParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventParameterList([NotNull] SolidityParser.EventParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.eventParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventParameterList([NotNull] SolidityParser.EventParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.eventParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventParameter([NotNull] SolidityParser.EventParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.eventParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventParameter([NotNull] SolidityParser.EventParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionTypeParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionTypeParameterList([NotNull] SolidityParser.FunctionTypeParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionTypeParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionTypeParameterList([NotNull] SolidityParser.FunctionTypeParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionTypeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionTypeParameter([NotNull] SolidityParser.FunctionTypeParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionTypeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionTypeParameter([NotNull] SolidityParser.FunctionTypeParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] SolidityParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] SolidityParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeName([NotNull] SolidityParser.TypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeName([NotNull] SolidityParser.TypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.userDefinedTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUserDefinedTypeName([NotNull] SolidityParser.UserDefinedTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.userDefinedTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUserDefinedTypeName([NotNull] SolidityParser.UserDefinedTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.mapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapping([NotNull] SolidityParser.MappingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.mapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapping([NotNull] SolidityParser.MappingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionTypeName([NotNull] SolidityParser.FunctionTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionTypeName([NotNull] SolidityParser.FunctionTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.storageLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStorageLocation([NotNull] SolidityParser.StorageLocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.storageLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStorageLocation([NotNull] SolidityParser.StorageLocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.stateMutability"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStateMutability([NotNull] SolidityParser.StateMutabilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.stateMutability"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStateMutability([NotNull] SolidityParser.StateMutabilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] SolidityParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] SolidityParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] SolidityParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] SolidityParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] SolidityParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] SolidityParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] SolidityParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] SolidityParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] SolidityParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] SolidityParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.simpleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleStatement([NotNull] SolidityParser.SimpleStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.simpleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleStatement([NotNull] SolidityParser.SimpleStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] SolidityParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] SolidityParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.inlineAssemblyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineAssemblyStatement([NotNull] SolidityParser.InlineAssemblyStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.inlineAssemblyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineAssemblyStatement([NotNull] SolidityParser.InlineAssemblyStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhileStatement([NotNull] SolidityParser.DoWhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhileStatement([NotNull] SolidityParser.DoWhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] SolidityParser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] SolidityParser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] SolidityParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] SolidityParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] SolidityParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] SolidityParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.throwStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrowStatement([NotNull] SolidityParser.ThrowStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.throwStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrowStatement([NotNull] SolidityParser.ThrowStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.emitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmitStatement([NotNull] SolidityParser.EmitStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.emitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmitStatement([NotNull] SolidityParser.EmitStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.variableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarationStatement([NotNull] SolidityParser.VariableDeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.variableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarationStatement([NotNull] SolidityParser.VariableDeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.variableDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarationList([NotNull] SolidityParser.VariableDeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.variableDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarationList([NotNull] SolidityParser.VariableDeclarationListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierList([NotNull] SolidityParser.IdentifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierList([NotNull] SolidityParser.IdentifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.elementaryTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementaryTypeName([NotNull] SolidityParser.ElementaryTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.elementaryTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementaryTypeName([NotNull] SolidityParser.ElementaryTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] SolidityParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] SolidityParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] SolidityParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] SolidityParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] SolidityParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] SolidityParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.nameValueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameValueList([NotNull] SolidityParser.NameValueListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.nameValueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameValueList([NotNull] SolidityParser.NameValueListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.nameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameValue([NotNull] SolidityParser.NameValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.nameValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameValue([NotNull] SolidityParser.NameValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionCallArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallArguments([NotNull] SolidityParser.FunctionCallArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionCallArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallArguments([NotNull] SolidityParser.FunctionCallArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] SolidityParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] SolidityParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyBlock([NotNull] SolidityParser.AssemblyBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyBlock([NotNull] SolidityParser.AssemblyBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyItem([NotNull] SolidityParser.AssemblyItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyItem([NotNull] SolidityParser.AssemblyItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyExpression([NotNull] SolidityParser.AssemblyExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyExpression([NotNull] SolidityParser.AssemblyExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyCall([NotNull] SolidityParser.AssemblyCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyCall([NotNull] SolidityParser.AssemblyCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyLocalDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyLocalDefinition([NotNull] SolidityParser.AssemblyLocalDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyLocalDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyLocalDefinition([NotNull] SolidityParser.AssemblyLocalDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyAssignment([NotNull] SolidityParser.AssemblyAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyAssignment([NotNull] SolidityParser.AssemblyAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyIdentifierOrList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyIdentifierOrList([NotNull] SolidityParser.AssemblyIdentifierOrListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyIdentifierOrList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyIdentifierOrList([NotNull] SolidityParser.AssemblyIdentifierOrListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyIdentifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyIdentifierList([NotNull] SolidityParser.AssemblyIdentifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyIdentifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyIdentifierList([NotNull] SolidityParser.AssemblyIdentifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyStackAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyStackAssignment([NotNull] SolidityParser.AssemblyStackAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyStackAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyStackAssignment([NotNull] SolidityParser.AssemblyStackAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.labelDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabelDefinition([NotNull] SolidityParser.LabelDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.labelDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabelDefinition([NotNull] SolidityParser.LabelDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblySwitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblySwitch([NotNull] SolidityParser.AssemblySwitchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblySwitch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblySwitch([NotNull] SolidityParser.AssemblySwitchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyCase([NotNull] SolidityParser.AssemblyCaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyCase([NotNull] SolidityParser.AssemblyCaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyFunctionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyFunctionDefinition([NotNull] SolidityParser.AssemblyFunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyFunctionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyFunctionDefinition([NotNull] SolidityParser.AssemblyFunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyFunctionReturns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyFunctionReturns([NotNull] SolidityParser.AssemblyFunctionReturnsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyFunctionReturns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyFunctionReturns([NotNull] SolidityParser.AssemblyFunctionReturnsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyFor([NotNull] SolidityParser.AssemblyForContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyFor([NotNull] SolidityParser.AssemblyForContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyIf([NotNull] SolidityParser.AssemblyIfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyIf([NotNull] SolidityParser.AssemblyIfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssemblyLiteral([NotNull] SolidityParser.AssemblyLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssemblyLiteral([NotNull] SolidityParser.AssemblyLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.subAssembly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubAssembly([NotNull] SolidityParser.SubAssemblyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.subAssembly"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubAssembly([NotNull] SolidityParser.SubAssemblyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.tupleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleExpression([NotNull] SolidityParser.TupleExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.tupleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleExpression([NotNull] SolidityParser.TupleExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.elementaryTypeNameExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementaryTypeNameExpression([NotNull] SolidityParser.ElementaryTypeNameExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.elementaryTypeNameExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementaryTypeNameExpression([NotNull] SolidityParser.ElementaryTypeNameExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.numberLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberLiteral([NotNull] SolidityParser.NumberLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.numberLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberLiteral([NotNull] SolidityParser.NumberLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] SolidityParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] SolidityParser.IdentifierContext context);
}
