//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Solidity.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISolidityListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class SolidityBaseListener : ISolidityListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.sourceUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSourceUnit([NotNull] SolidityParser.SourceUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.sourceUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSourceUnit([NotNull] SolidityParser.SourceUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.pragmaDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragmaDirective([NotNull] SolidityParser.PragmaDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.pragmaDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragmaDirective([NotNull] SolidityParser.PragmaDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.pragmaName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragmaName([NotNull] SolidityParser.PragmaNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.pragmaName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragmaName([NotNull] SolidityParser.PragmaNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.pragmaValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragmaValue([NotNull] SolidityParser.PragmaValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.pragmaValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragmaValue([NotNull] SolidityParser.PragmaValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.version"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVersion([NotNull] SolidityParser.VersionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.version"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVersion([NotNull] SolidityParser.VersionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.versionOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVersionOperator([NotNull] SolidityParser.VersionOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.versionOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVersionOperator([NotNull] SolidityParser.VersionOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.versionConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVersionConstraint([NotNull] SolidityParser.VersionConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.versionConstraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVersionConstraint([NotNull] SolidityParser.VersionConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.importDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportDeclaration([NotNull] SolidityParser.ImportDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.importDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportDeclaration([NotNull] SolidityParser.ImportDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.importDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportDirective([NotNull] SolidityParser.ImportDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.importDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportDirective([NotNull] SolidityParser.ImportDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.natSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNatSpec([NotNull] SolidityParser.NatSpecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.natSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNatSpec([NotNull] SolidityParser.NatSpecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.contractDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContractDefinition([NotNull] SolidityParser.ContractDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.contractDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContractDefinition([NotNull] SolidityParser.ContractDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.inheritanceSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInheritanceSpecifier([NotNull] SolidityParser.InheritanceSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.inheritanceSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInheritanceSpecifier([NotNull] SolidityParser.InheritanceSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.contractPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContractPart([NotNull] SolidityParser.ContractPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.contractPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContractPart([NotNull] SolidityParser.ContractPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.stateVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateVariableDeclaration([NotNull] SolidityParser.StateVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.stateVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateVariableDeclaration([NotNull] SolidityParser.StateVariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.usingForDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingForDeclaration([NotNull] SolidityParser.UsingForDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.usingForDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingForDeclaration([NotNull] SolidityParser.UsingForDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.structDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDefinition([NotNull] SolidityParser.StructDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.structDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDefinition([NotNull] SolidityParser.StructDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.constructorDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorDefinition([NotNull] SolidityParser.ConstructorDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.constructorDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorDefinition([NotNull] SolidityParser.ConstructorDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.modifierDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifierDefinition([NotNull] SolidityParser.ModifierDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.modifierDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifierDefinition([NotNull] SolidityParser.ModifierDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.modifierInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifierInvocation([NotNull] SolidityParser.ModifierInvocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.modifierInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifierInvocation([NotNull] SolidityParser.ModifierInvocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDefinition([NotNull] SolidityParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDefinition([NotNull] SolidityParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.returnParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnParameters([NotNull] SolidityParser.ReturnParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.returnParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnParameters([NotNull] SolidityParser.ReturnParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.modifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifierList([NotNull] SolidityParser.ModifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.modifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifierList([NotNull] SolidityParser.ModifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.eventDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventDefinition([NotNull] SolidityParser.EventDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.eventDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventDefinition([NotNull] SolidityParser.EventDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValue([NotNull] SolidityParser.EnumValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValue([NotNull] SolidityParser.EnumValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.enumDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDefinition([NotNull] SolidityParser.EnumDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.enumDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDefinition([NotNull] SolidityParser.EnumDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] SolidityParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] SolidityParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] SolidityParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] SolidityParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.eventParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventParameterList([NotNull] SolidityParser.EventParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.eventParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventParameterList([NotNull] SolidityParser.EventParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.eventParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventParameter([NotNull] SolidityParser.EventParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.eventParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventParameter([NotNull] SolidityParser.EventParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionTypeParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionTypeParameterList([NotNull] SolidityParser.FunctionTypeParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionTypeParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionTypeParameterList([NotNull] SolidityParser.FunctionTypeParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionTypeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionTypeParameter([NotNull] SolidityParser.FunctionTypeParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionTypeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionTypeParameter([NotNull] SolidityParser.FunctionTypeParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] SolidityParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] SolidityParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] SolidityParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] SolidityParser.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.userDefinedTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUserDefinedTypeName([NotNull] SolidityParser.UserDefinedTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.userDefinedTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUserDefinedTypeName([NotNull] SolidityParser.UserDefinedTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.mapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapping([NotNull] SolidityParser.MappingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.mapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapping([NotNull] SolidityParser.MappingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionTypeName([NotNull] SolidityParser.FunctionTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionTypeName([NotNull] SolidityParser.FunctionTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.storageLocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStorageLocation([NotNull] SolidityParser.StorageLocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.storageLocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStorageLocation([NotNull] SolidityParser.StorageLocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.stateMutability"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStateMutability([NotNull] SolidityParser.StateMutabilityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.stateMutability"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStateMutability([NotNull] SolidityParser.StateMutabilityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] SolidityParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] SolidityParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] SolidityParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] SolidityParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] SolidityParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] SolidityParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] SolidityParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] SolidityParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] SolidityParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] SolidityParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.simpleStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleStatement([NotNull] SolidityParser.SimpleStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.simpleStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleStatement([NotNull] SolidityParser.SimpleStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] SolidityParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] SolidityParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.inlineAssemblyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineAssemblyStatement([NotNull] SolidityParser.InlineAssemblyStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.inlineAssemblyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineAssemblyStatement([NotNull] SolidityParser.InlineAssemblyStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.doWhileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoWhileStatement([NotNull] SolidityParser.DoWhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.doWhileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoWhileStatement([NotNull] SolidityParser.DoWhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] SolidityParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] SolidityParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] SolidityParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] SolidityParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] SolidityParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] SolidityParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.throwStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThrowStatement([NotNull] SolidityParser.ThrowStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.throwStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThrowStatement([NotNull] SolidityParser.ThrowStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.emitStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmitStatement([NotNull] SolidityParser.EmitStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.emitStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmitStatement([NotNull] SolidityParser.EmitStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.variableDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarationStatement([NotNull] SolidityParser.VariableDeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.variableDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarationStatement([NotNull] SolidityParser.VariableDeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.variableDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarationList([NotNull] SolidityParser.VariableDeclarationListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.variableDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarationList([NotNull] SolidityParser.VariableDeclarationListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierList([NotNull] SolidityParser.IdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierList([NotNull] SolidityParser.IdentifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.elementaryTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementaryTypeName([NotNull] SolidityParser.ElementaryTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.elementaryTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementaryTypeName([NotNull] SolidityParser.ElementaryTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] SolidityParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] SolidityParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpression([NotNull] SolidityParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpression([NotNull] SolidityParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] SolidityParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] SolidityParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.nameValueList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameValueList([NotNull] SolidityParser.NameValueListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.nameValueList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameValueList([NotNull] SolidityParser.NameValueListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.nameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameValue([NotNull] SolidityParser.NameValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.nameValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameValue([NotNull] SolidityParser.NameValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionCallArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCallArguments([NotNull] SolidityParser.FunctionCallArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionCallArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCallArguments([NotNull] SolidityParser.FunctionCallArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] SolidityParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] SolidityParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyBlock([NotNull] SolidityParser.AssemblyBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyBlock([NotNull] SolidityParser.AssemblyBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyItem([NotNull] SolidityParser.AssemblyItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyItem([NotNull] SolidityParser.AssemblyItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyExpression([NotNull] SolidityParser.AssemblyExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyExpression([NotNull] SolidityParser.AssemblyExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyCall([NotNull] SolidityParser.AssemblyCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyCall([NotNull] SolidityParser.AssemblyCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyLocalDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyLocalDefinition([NotNull] SolidityParser.AssemblyLocalDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyLocalDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyLocalDefinition([NotNull] SolidityParser.AssemblyLocalDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyAssignment([NotNull] SolidityParser.AssemblyAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyAssignment([NotNull] SolidityParser.AssemblyAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyIdentifierOrList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyIdentifierOrList([NotNull] SolidityParser.AssemblyIdentifierOrListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyIdentifierOrList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyIdentifierOrList([NotNull] SolidityParser.AssemblyIdentifierOrListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyIdentifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyIdentifierList([NotNull] SolidityParser.AssemblyIdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyIdentifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyIdentifierList([NotNull] SolidityParser.AssemblyIdentifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyStackAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyStackAssignment([NotNull] SolidityParser.AssemblyStackAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyStackAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyStackAssignment([NotNull] SolidityParser.AssemblyStackAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.labelDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabelDefinition([NotNull] SolidityParser.LabelDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.labelDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabelDefinition([NotNull] SolidityParser.LabelDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblySwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblySwitch([NotNull] SolidityParser.AssemblySwitchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblySwitch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblySwitch([NotNull] SolidityParser.AssemblySwitchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyCase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyCase([NotNull] SolidityParser.AssemblyCaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyCase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyCase([NotNull] SolidityParser.AssemblyCaseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyFunctionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyFunctionDefinition([NotNull] SolidityParser.AssemblyFunctionDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyFunctionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyFunctionDefinition([NotNull] SolidityParser.AssemblyFunctionDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyFunctionReturns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyFunctionReturns([NotNull] SolidityParser.AssemblyFunctionReturnsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyFunctionReturns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyFunctionReturns([NotNull] SolidityParser.AssemblyFunctionReturnsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyFor([NotNull] SolidityParser.AssemblyForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyFor([NotNull] SolidityParser.AssemblyForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyIf([NotNull] SolidityParser.AssemblyIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyIf([NotNull] SolidityParser.AssemblyIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.assemblyLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssemblyLiteral([NotNull] SolidityParser.AssemblyLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.assemblyLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssemblyLiteral([NotNull] SolidityParser.AssemblyLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.subAssembly"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubAssembly([NotNull] SolidityParser.SubAssemblyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.subAssembly"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubAssembly([NotNull] SolidityParser.SubAssemblyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.tupleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleExpression([NotNull] SolidityParser.TupleExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.tupleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleExpression([NotNull] SolidityParser.TupleExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.elementaryTypeNameExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementaryTypeNameExpression([NotNull] SolidityParser.ElementaryTypeNameExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.elementaryTypeNameExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementaryTypeNameExpression([NotNull] SolidityParser.ElementaryTypeNameExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.numberLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberLiteral([NotNull] SolidityParser.NumberLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.numberLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberLiteral([NotNull] SolidityParser.NumberLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidityParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] SolidityParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidityParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] SolidityParser.IdentifierContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
